### ISSUE TITLE
item inside CM disappear when broke

### ISSUE THREAD

**Issue by poiju87** [thraaawn/CompactMachines#101]
I am using the latest version of this mod, also it happens inside a Giant (diamond) compact machine. I have better barrels from JABBA inside, Tesseract from thermal expansion, conduits from Ender IO and liquids such as water and lava to create a cobble gen using transfer node (item) from Extra Utilities. when I break a blocks (any) inside the Compact Machine, it disappears into the void. Any idea how to fix this? maybe I am using too many entities with my cobble gen? (I have 35 transfer node with respectively 64 world interaction upgrade in them generating cobblestones). Any help is appreciated.

**Comment by thraaawn** [comment]
Two options:
a) Upgrade the CM with a Nether Star so it retains its content when being broken.
b) Set the maxDroppedStacks option in the config file to -1 to always drop all stacks when breaking a CM.

**Comment by poiju87** [comment]
blocks broken INSIDE the compact machines disappears into the void, I did not break the compact machine and fyi it is already equiped with a nether star and the maxDroppedStacks is already set to -1

**Comment by zortordor** [comment]
can confirm, blocks disappear when broken inside the machine
