### ISSUE TITLE
Lock CM to owner enhancement

### ISSUE THREAD

**Issue by baconsandvich** [thraaawn/CompactMachines#102]
Add the ability to lock the machines to the owner who placed them. It can be set up like Thermal Expansions locking system. Expanding on this concept you can add guests/friends to your locked machine too.

**Comment by Badcholo** [comment]
Add a config to remove this feature please. Some servers are raid/grief.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
