### ISSUE TITLE
Configurable energy throughput

### ISSUE THREAD

**Issue by XFactHD** [thraaawn/CompactMachines#104]
Does the Interface of a CM have a maximum energy throughput?

**Comment by NPException42** [comment]
as far as I'm aware, yes. See here: https://github.com/thraaawn/CompactMachines/blob/f44ef145f65638ede10f3e0e8f7ae585c955a322/src/main/java/org/dave/CompactMachines/integration/redstoneflux/FluxSharedStorage.java#L17

**Comment by thraaawn** [comment]
By default 10000 RF/t. You can change that in the configuration.

**Comment by XFactHD** [comment]
I have looked into the configuration file and I am not seeing an option to change the throughput.

**Comment by thraaawn** [comment]
Oups, my bad. You are right. I thought I added that long time ago, but apparently I didn't.

**Comment by XFactHD** [comment]
I just had another idea for the configuration: Could you make the player be able to on one hand configure an absolute maximum of throughput in the config file and on the other hand let him configure the amount of energy between zero and the config setting by inserting a certain Thermal Dynamics Flux Duct into the interface's slot if the  above mentioned mod is installed.

**Comment by thraaawn** [comment]
For now only config file configuration. Implemented in 3f6c8e28395e9c11d31ec1239437ccb4de5bb146.
