### ISSUE TITLE
Crash upon leaving the compact machine

### ISSUE THREAD

**Issue by Badcholo** [thraaawn/CompactMachines#107]
When i leave the compact machine using the remote thingy i get this crash.
SSP
http://pastebin.com/WG1RKFDw

**Comment by thraaawn** [comment]
I need more information. Which versions are you using? Do you have any mod that unloads the overworld even though it should always be loaded?

**Comment by Badcholo** [comment]
sorry it was not your mod that was causing the problem. It was TooMuchTime, Their last version was causing overworld to become unloaded for some reason. Their latest version has fixed this and your mod works great. I will continue testing it to find bugs or glitches. I love your mod thank you so much for making it!!!! i had to go thru 100 mods to find this, i never would have guessed it was TooMuchTime. you can close this.

**Comment by thraaawn** [comment]
You are welcome, cheers!
