### ISSUE TITLE
[Suggestion] make sides configurable to Import/Export

### ISSUE THREAD

**Issue by tgstyle** [thraaawn/CompactMachines#108]
I know it would be a bit of work, but this would be a "nice to have". A lot of different mods machines can do in/out on the same side, it would be nice to have 2 separate buffers going in either direction on the same side. The modes could be Import, Export, Import/Export, Disabled, and Auto.

**Comment by XFactHD** [comment]
I think that is already possible, you have the modes Import, Export, Automatic and Disabled.

**Comment by thraaawn** [comment]
Sorry, I won't support two item buffers per side.
