### ISSUE TITLE
Fell into void using Mystcraft

### ISSUE THREAD

**Issue by Alzarath** [thraaawn/CompactMachines#111]
So interesting thing happened. I've started to set up a Compact Machine that I'd use as sort of a teleportation hub. When entering the hub through a book, I got Wither and Nausea. I then proceeded to fall through the world and die in the void. I assume this has something to do with trying to force players to stay in the boxes and, since I didn't enter through a block, it didn't know where to put me.

**Comment by thraaawn** [comment]
> When entering the hub through a book, I got Wither and Nausea.
This is intended.

> I then proceeded to fall through the world and die in the void
This isn't. I will look into it.
