### ISSUE TITLE
COFH energy api outdated in 1.18

### ISSUE THREAD

**Issue by Surrogard** [thraaawn/CompactMachines#113]
The COFH energy API shipped with 1.18 (current stable?) seems to be out of date and crashes the server if there is another mod using the new API (like EnderIO 2.2.8.349). It runs fine if I delete the cofh/api/energy folder from the JAR so that CompactMachines is using the new API, but that is of course only a temporal measure.

Regards
Surrogard

**Comment by ShadowDrakken** [comment]
Running into the same issue. The second I attached an itemduct the server crashed and is unrecoverable without MCEdit. Removing the cofh/api/energy folder didn't help at all.

**Comment by Surrogard** [comment]
@ShadowDrakken: this sounds like a different issue. For me the "offending" block was a powerconduit from enderIO. I don't know if itemduct can transport RF.

**Comment by thraaawn** [comment]
Definitely a different issue. @ShadowDrakken please open a new issue and attach a pastebin of the crash log.
@Surrogard, i will look into it soonish, but I thought I already did that a while ago.

**Comment by ShadowDrakken** [comment]
How's it a different issue? It's outdated Thermal Dynamics support, plain and simple. Whatever.

**Comment by Surrogard** [comment]
@ShadowDrakken: well this issue is about outdated COFH energy api, so I cannot see how this possibly could be the same ;)
@thraaawn perhaps in the 1.19? I'm beta enough with my server so I didn't want to test the 1.19 beta...

**Comment by XFactHD** [comment]
@ShadowDrakken Your problem might have something to do with the CoFH api, but not with the CoFH energy api.

@Surrogard With what sort of stack trace does your game crash? Can you post the crash report on pastebin?

**Comment by thraaawn** [comment]
@ShadowDrakken, @Surrogard, I cannot reproduce your issues, please provide a crash report.

**Comment by Surrogard** [comment]
Hi @thraaawn, sorry for the late reply: http://pastebin.com/CU6wQzHn
I can also provide you with a server log if needed

Be

Surrogard

thraaawn <notifications@github.com> schrieb am Sa., 9. Mai 2015 13:48:
