### ISSUE TITLE
Changable light level in machines

### ISSUE THREAD

**Issue by Surrogard** [thraaawn/CompactMachines#114]
Hi,

it seems the light level in the machines is fixed (I guess it's tied to the dimension where the boxes are). Would it be possible to change that individually? Even if I pad the walls with stone the light level doesn't change which unfortunately makes the use of spawners in boxes impossible right now.

**Comment by thraaawn** [comment]
This is planned. CM will get upgrade slots at some point in the future, one of them will be "Sunlight". Details are still unclear.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
