### ISSUE TITLE
Death upon enter a CM with RFTools installed.

### ISSUE THREAD

**Issue by GeoZakum** [thraaawn/CompactMachines#116]
CM version 1.18
RFTools version: 2.75 & 2.82

With 2.75 the game doesnt load due to RFTools erroring on start up but with 2.82 the game starts fine however upong entering a cube the player is killed the same way they would be if a RFtools dimension ran out of power.Not sure which mod is at fault so posting here as bug. 

When i broke the machine which caused my death i also noticed that alot of cobble and Chisel Diorite came out, generation/dimension bug?
Perhaps a new ID for the dimension would fix it but i do not wish to tinker with that.

**Comment by thraaawn** [comment]
Looks like RFTools thinks the CM dimension would belong to it.
@McJty, any idea how that might happen?

**Comment by McJty** [comment]
Hmm. This could happen if during update some mod (like CM or whatever) suddenly decides to register a dimension that you have previously already created with rftools. The problem is that rftools creates dimensions dynamically. To solve this you should change the CM config to let it use another dimension id.

**Comment by GeoZakum** [comment]
Im not the best at these things, what would said ID be? I mentioned that probably that would be the solution but i have no clue to which number to change it to since i have no clue how the coding works.

**Comment by McJty** [comment]
Basically you have to use a number that is not already taken by any other dimension mod. If you do the /rftdim list in game then you can see the RFTools dimensions at least so you can avoid those ids.

**Comment by GeoZakum** [comment]
So give it an ID not currently in use? Alright, i will try that now.
-
Alright, please excuse the long 2~ hour wait,personal ssues, but yes that did indeed resolve the issue.I moved the CM dimension to ID -2 and upon entering all was fine. By what i looked in the IDs for Rft dimension they seemed to follow the positive line so all should be good.
Thank you for the assistance!

**Comment by McJty** [comment]
Ok, glad this got resolved then :-)
