### ISSUE TITLE
Crash when on ladder while holding personal shrinking device. 

### ISSUE THREAD

**Issue by lehjr** [thraaawn/CompactMachines#117]
First reported here by another user:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2220422-compact-machines-v1-18?comment=111

I ran into this myself today. http://pastebin.com/JWAg7kFi Not really sure what causes it.

**Comment by thraaawn** [comment]
Thanks for the report, I will look into it.

**Comment by thraaawn** [comment]
I could not reproduce this, will add some npe checks anyway.

**Comment by lehjr** [comment]
I did just tried a test build and can confirm that solved it the issue, though I still don't really know what exactly caused the issue.
