### ISSUE TITLE
Input only/output only/disabled modes

### ISSUE THREAD

**Issue by SoniEx2** [thraaawn/CompactMachines#118]
I'd like to be able to configure each side to be either input and output, input only, output only, or disabled. An input only side would only accept things going in, an output only side would only accept things coming out, a disabled side would not let anything interact with it (energy/fluid methods would return that it can't connect on the given side, ISidedInventory would return no slots, etc).

**Comment by XFactHD** [comment]
Input only and output only is already possible, the interface can also be deactivated and in another issue thraawn stated that input and output on the same side won't come.

**Comment by SoniEx2** [comment]
No, he said he won't support 2 buffers on the same side.

I'm not asking for 2 buffers on the same side, I'm asking for a single buffer (the way it is now), but only allow access to it depending on input/output flags. (e.g. `if (wantsToInput && canInput) return buffer; if (!wantsToInput && canOutput) return buffer; return null;`)

**Comment by thraaawn** [comment]
I will change I/O a bit once I've added upgrades to CM. Might be a while.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
