### ISSUE TITLE
Compact Machines gas I/O Crashes

### ISSUE THREAD

**Issue by juniorjunior** [thraaawn/CompactMachines#121]
EnderIO Crash: http://pastebin.com/vGtPVPey
Galacticraft Crash: http://pastebin.com/CGiWqAww

Compact Machines 1.19-fluids-preview-b5
Galacticraft 3.0.12.336
EnderIO 2.3.0.378

Any attempt to move gases from GC or EIO through a Compact Machines block crashes the client/server. This occurs with EIO Gas Conduits and with side-adjacent machines.

**Comment by thraaawn** [comment]
Which Mekanism version are you using?

**Comment by juniorjunior** [comment]
Mekanism 8.1.2.229

**Comment by ZeekDaGeek** [comment]
I have the exact same issue.

Complete mod list with versions: https://docs.google.com/a/graythought.com/spreadsheet/ccc?key=0AndvSyXha_pPdHRYTXVtNVpHSzhrNjZxTDAzS2V3UEE&usp=sharing#gid=0

**Comment by ZeekDaGeek** [comment]
Sorry, I accidentally submitted before writing the full extent of the details:

Here is the test case:

http://zeekdageek.tv/ss/durfq.png

- Water is fed into a Mekanism Separator, the method does not matter.
- The water is converted with power into Hydrogen and Oxygen gas. The gas is automatically pumped to the near by Tank which pushes it through the EnderIO pipes.
- At the end of the pipe is an additional tank to see if it ever reaches the destination.

The setup has 3 intended tests.  Closest row is the control, going through the system with no issues. The second and third ones are the issue.

Second row has a fully formed Compact Machine, inside it has pipes that allow the gas to simply pass through, the right side set to an import, the left side set to an output.

The third row is the same but the Compact Machine has not been formed yet, it was never right clicked to create the space in the other dimension.

Any time you provide power to the electrolyser in the Compact Machine systems the server crashes instantly, you can not load the world again either, it crashes immediately.

**Comment by thraaawn** [comment]
Would you mind retesting with this patch before I release a proper new version?
Grab the latest build from [here](http://goo.gl/1ysU9U).

**Comment by juniorjunior** [comment]
Just for the sake of completeness, I tested this in both a new world and in an existing world that had crashed from this issue and both worked perfectly. Thank you!
