### ISSUE TITLE
Feature Suggestion: SleepChambers

### ISSUE THREAD

**Issue by Badcholo** [thraaawn/CompactMachines#122]
I would like to suggest a Sleeping Chamber. A compact machine that's only purpose is to make more living space. possibly not so high but more wide. Like a 13X13X5. I can already use a different mod to paint the walls and it's awsome. No input/output.

**Comment by thraaawn** [comment]
No, can already be achieved using normal CMs. Just built your own ceiling in it if you want to reduce the size.

**Comment by Badcholo** [comment]
yeah, your right. I just found out how to upgrade the machines. wow!! just wow!!
