### ISSUE TITLE
Something Very Wrong. Multiplayer

### ISSUE THREAD

**Issue by Badcholo** [thraaawn/CompactMachines#124]
compactmachines-1.7.10-1.18
So uhm I have installed this on my server and Modpack, Mojangsters. It Seems that the Tiny compact machine is conflicting with the Max size compact machine. They are both spawnign in the same space. I have taken screenshots of the issue. Hope it gets fixed soon. Also is there any way to break those blocks in creative mode or Op so i can fix the problem?
![2015-05-17_22 18 19](https://cloud.githubusercontent.com/assets/10932905/7674730/3fe1b09e-fce3-11e4-9257-263e2a34e083.png)
![2015-05-17_22 18 57](https://cloud.githubusercontent.com/assets/10932905/7674731/3fe348c8-fce3-11e4-86bf-69eea2f021c3.png)
![2015-05-17_22 22 13](https://cloud.githubusercontent.com/assets/10932905/7674732/42aa6690-fce3-11e4-9187-251419f8b22e.png)

**Comment by Badcholo** [comment]
![2015-05-17_22 36 03](https://cloud.githubusercontent.com/assets/10932905/7674857/2a1c64fa-fce5-11e4-8b67-e9845d56cf7d.png)

**Comment by Badcholo** [comment]
http://www.technicpack.net/modpack/mojangsters.583708

**Comment by Badcholo** [comment]
Also right clicking the machine bare hand causes the client to crash. 
http://pastebin.com/ktqW2xzZ
client logs
https://www.dropbox.com/sh/ss8w4ny1jfch3hl/AAAaBwCTXZyUkw93TvZgh2wLa?dl=0

**Comment by thraaawn** [comment]
* Somehow your world data got corrupted and CMs could not load the file indicating what the next CM coordinates are. Restore a backup.
* "One cross each", please don't mix problems in a single issue, anyway: You are not using the version compatible with the latest forge fluid changes. There's a preview version on curseforge, use that one.

**Comment by Badcholo** [comment]
dang... i had a feeling i corrupted the server world. Sorry i thought i only used the recommended file version cause i saw the newer one was a beta. Thank you so much for an amazing mod and your quick replies and help. I have quite a bit of work to do on my server now. oooff, man i gotta pregen a whole world again.
