### ISSUE TITLE
Allow entering machines via the GUI

### ISSUE THREAD

**Issue by Badcholo** [thraaawn/CompactMachines#129]
Would be nice to be able to just right click the machine to get Shrunk and get inside it or a Button within the gui as an upgrade. Press the button within the gui and get shrunk. Maybe Shift-Right Click. Upgrade the Machine with a new item crafted using a PSD. This allows players to shift-right click or a button within the right click gui and get into the CM. This will help so players don't get locked out of the machine or have to carry around a PSD.

**Comment by Maxiride** [comment]
I think the PSD enhance the importance of not loosing it =) Such improvement maybe could be added to a CM as an upgrade but not to default.

**Comment by Badcholo** [comment]
That's what i said.

**Comment by Maxiride** [comment]
Yeah I know, just wanted to reinforce the value of this idea and it's worth having it ;)

**Comment by Badcholo** [comment]
Thanks!!

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
