### ISSUE TITLE
Stuck?

### ISSUE THREAD

**Issue by JCBurnside** [thraaawn/CompactMachines#130]
So I added this mod to the Sky Factory 2.4 pack and entered a nether star tier Compact Machine and now when I try to interact with an interface it crashes my game so I can't leave.  (note:I am in a creative world.)

**Comment by thraaawn** [comment]
Crashlog please.

**Comment by JCBurnside** [comment]
the file is very large (it has to go through 151 mods) so i put it in pastebin.
this one is a crash where I clicked with an empty hand on the block http://pastebin.com/hQSBBtii
and this one is a crash inside the block when i clicked on the interface http://pastebin.com/ns29DSDR

**Comment by thraaawn** [comment]
Jupp, update to 1.19b and you should be good.

**Comment by JCBurnside** [comment]
thank you
