### ISSUE TITLE
crash when placing CMs 

### ISSUE THREAD

**Issue by abdullamu** [thraaawn/CompactMachines#131]
im guessing its because the biome adaptation 
http://pastebin.com/ptkAeWcc

**Comment by thraaawn** [comment]
Which biome did you place the CM in?

**Comment by thraaawn** [comment]
Thanks for the report. Hotfixed 1.19b is released. Sorry for the inconvenience!

**Comment by abdullamu** [comment]
thank you fine sir ,not at all
