### ISSUE TITLE
[Suggestion] Change wording on entanglement error

### ISSUE THREAD

**Issue by xenoflot** [thraaawn/CompactMachines#134]
Hi, I tried to entangle a couple of machines tonight. I hadn't read the manual, was just experimenting. I tapped the tangler on a machine and it reported "Can not entangle: Machine has never been used before." Got the same result on both, so I entered them both. Then I was told "Can not entangle: Machine is already in use." The problem remained after I'd applied netherstars. As a user I felt somewhat frustrated by the contradictory messages and angry that I'd wasted two nether stars on Tiny machines that I'll never use.

I suggest the first error be changed to "Can not entangle, you need to apply a netherstar to the machine first."

or if you're wanting to stay a little elusive about it, "Unstabilized machines cannot be entangled."

**Comment by thraaawn** [comment]
Sorry that happened to you.
I'm not sure how can I can communicate efficiently that one of the CMs needs to be used and one needs to be new. You should only have entered one of the CMs, but both need the upgrade.

Any ideas how to resolve this?

**Comment by xenoflot** [comment]
Thanks for the reply. A few ideas that revolve around clearly identifying masters and slaves.

1.Right clicking an uninitialized machine on an initialized machine will bind it to that parent with a report to that effect in the console. Simple but if you have multiple machines in your inventory, easy to get confused.

2. Similar to the Blood Magic Translocator, have an entanglement key item. Right click it on the parent and then put it in a GUI slot on a slave. An initialised machine would have a flag set that hides the keyhole. More clearly defines which is master and which is slave.

3. Similar to AE2's quantum bridges, create an entangled pair that you place one of each in each of the machines to be entangled. Allow keys to be named. Very clearly identifies which machines are linked however restricts you to only 2 entangled machines.

4. An expansion of 2. Craft some Entanglement Upgrades in addition to one machine. Apply one upgrade to the initialized machine (until it's initialized, the upgrade won't stick). After it's initialized and upgraded, three GUI slots appear in the machine. A Name field an input and output slot. Once the machine has been given a name, additional Entanglement Upgrades can be placed in the input slot. They will be named and returned as placeable machines with the same name as the parent.

Number 4 is my preference as it's a simple and clear process that I expect isn't prone to any misunderstanding. You actually use your internal UUID for the entanglement which allows for the machine to be renamed as the user desires, although you may want to add some duplicate checking to prevent the user accidentally creating two masters with the same Name. You may or may not care for the entanglement to be retained if the master is broken.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
