### ISSUE TITLE
Random Things spectre issue

### ISSUE THREAD

**Issue by tgstyle** [thraaawn/CompactMachines#136]
So I am not sure if this is a Random Things issue or a Compact Machines issue. If you place a compact machine in the spectre, and use the Personal Shrinking Device to enter it. Upon returning to the spectre with the PSD and using the spectre key to exit, it puts you back inside the compact machine. Then you are stuck in the spectre with no way out unless you can teleport out somehow.

RT 2.2.4
CM 1.19b

**Comment by thraaawn** [comment]
You probably ran an older version of CM before updating?
Try placing a CM in your specter dim, enter it and leave it. You should land back in the overworld.

**Comment by tgstyle** [comment]
The only other version I used was 1.19 preview. Leave it how, with the spectre key or the PSD? Using the PSD puts me back in the spectre.

**Comment by tgstyle** [comment]
Tested again and leaving the CM with the spectre key or PSD always puts my back in the spectre.

**Comment by tgstyle** [comment]
Then using the spectre key again and it puts me inside the CM. There is no way back to the overworld.

**Comment by tgstyle** [comment]
I tested a clean server, a clean single player and the same thing happens. I place the CM in the spectre, enter it with the PSD, exit with the PSD, it puts me in the spectre, try to exit the spectre with the key and it puts me back in the CM. I have tried exiting the CM with the spectre key, it puts me in the spectre, then try to exit the spectre with the key, it puts me in the CM.
