### ISSUE TITLE
Bungeecord issue with Compact Machines Dimension

### ISSUE THREAD

**Issue by devryb** [thraaawn/CompactMachines#137]
Hi when using Bungeecord and moving to a server with Compact Machines mod installed clients get a Fatal Error.  This only happens if they moved from the server with CM to a hub server and then back to the server with CM on it.  If the player joins the hub server first and moves to the server with CM the fatal error doesn't happen.

Here is the clients log when trying to move servers and the fatal error occurs:
It looks like according to the log the client is holding information about dimension 3 after moving to the hub.

http://pastebin.com/RK4FW1vP

Version 1.19B

**Comment by MJRLegends** [comment]
@thraaawn is this going to be ever fixed???

**Comment by thraaawn** [comment]
There won't be another 1.7.10 version. A 1.10.2 version is in the works, but is going slowly at the moment.

**Comment by MJRLegends** [comment]
So this major problem is just going to stay broken ok.....

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
