### ISSUE TITLE
Tier Rework

### ISSUE THREAD

**Issue by Alzarath** [thraaawn/CompactMachines#138]
Making the interfaces themselves is the most tedious and generally resource-intensive part of the mod. It's a pretty intricate process. After all that, the tier selection is very underwhelming. It's a boring resource sink (8 of an item around the block to choose its tier? Come on). Anything under obsidian tier is going to feel like a waste of all the resources it took to make the interfaces. Anything above it is unreasonably expensive.

I feel like the entire tier system needs some kind of rework. Maybe tiered interface panels? I'd like to see discussion on it.

**Comment by thraaawn** [comment]
I agree and am open to suggestions.

**Comment by pip69** [comment]
To go along with power requirements, have different Tiers use a power multiplier for upgrades.  So you  could have the smaller CM cheap or free to use upgrades.

Just random thoughts
 - a specific machine to make CM
 - ^ above is actually the inside of a Tiny CM 
 - able to make a CM bigger after it's built/used

**Comment by DoctorTardi** [comment]
Perhaps requiring a source of power to maintain the inner dimension?

**Comment by Maxiride** [comment]
I would really discourage the need of power to maintain the inner dimension, it will just be an hassle.
Regarding the recipe for the compact machines, as for the actual state of the mod, I think is balanced and not at all a resource waster, 8 of an item it's so cheap. I would agree only for the maximum size which requires 8 nether stars, if all the tiers has some kind of "linear" progression the biggest compact machine is waaay too much expensive. Instead 8 blocks of diamonds imho suit better the case.

The nether star price to upgrade them and entangle them seems reasonable instead.

Honestly speaking for the great advantage you take from a compact machine, it's price in terms of recipe resources it's worth it.

I see this mod more like a middle to end game thing.

**Comment by Badcholo** [comment]
It would be nice to be able to upgrade the cm size, but i understand that it would mean a new area in the dimension. That means that if you have anything in the small CM and upgrade it you'll get a new room and lose all your stuff in the old room. unless you figure out a way to expand that same room and delete the walls and expand the room, but that seems quite hard to do from a programming point. I like the way it is now.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
