### ISSUE TITLE
Crash on attempt to enter a Machine

### ISSUE THREAD

**Issue by tylerk196** [thraaawn/CompactMachines#140]
Whenever I attempt to enter a machine, any type, I get to the point where I can see the sky but the machine walls themselves haven't loaded yet and then it crashes. I tested it without Optifine and it still happened.

http://pastebin.com/p8TFyY6J -- Optifine
http://pastebin.com/hD5rty7V -- No Optifine

**Comment by XFactHD** [comment]
Which version of AE2 and Compact Machines are you using?

**Comment by tylerk196** [comment]
The latest version on the curse voice beta client, Compact Machines 1.7.10-1.19b and AE2 rv2-stable-9

**Comment by XFactHD** [comment]
That is strange because the crash you are getting should only happen if you use this version of Compact Machines with AE2 rv1.
@thatsIch any idea what is going on here?

**Comment by thatsIch** [comment]
> Caused by: java.lang.ClassNotFoundException: mekanism.api.gas.GasStack

hard dependency on Mekanism? It is imo just coincidence that it crashed there, cause it was evaluated in the EventBus first.
