### ISSUE TITLE
Ability to shrink yourself in the CM dimension

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#150]
Basically like morph, shrink to less than one block size.
Might be a good upgrade once the upgrade system arrives?

**Comment by Saereth** [comment]
that would be great, especially on servers that dont have morph. Could also be something that works outside of a CM using the power of the PSD perhaps?

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
