### ISSUE TITLE
World crashloop, already existing connection

### ISSUE THREAD

**Issue by Saereth** [thraaawn/CompactMachines#151]
This bug happened a few versions ago but seemed to be fixed, updated to the latest version and getting this again. CM was placed against an ME controller, there is not an other me connections to the CM. Server crashloops with this error until we mcedited out the controller

Full crash log:http://pastebin.com/4YdK7eju

Forge 1448 dedicated server running the Nuts and Bolts Pack (technic)

Happy to provide any additional information.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
