### ISSUE TITLE
redstone input/output

### ISSUE THREAD

**Issue by anar4732** [thraaawn/CompactMachines#152]
redstone input/output can be added to

project red cables can be added to the input output

---

it has been translated into English from the Turkish language translation of this text by yandex

**Comment by demethan** [comment]
Redstone signal passthrough would be nice from any mod. 

Even vanilla rs signal would be a bonus.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
