### ISSUE TITLE
Apllied Energistics uptime

### ISSUE THREAD

**Issue by deathglow** [thraaawn/CompactMachines#154]
I am running resonant rise 3 pack from the atlauncher with code pxoVTdul.  I have a few of the max sized compact machines inside my base but the majority of my applied energistics system is not in one.  I have terminals and input and output buses on systems inside these compact machines.  I use mostly ender conduit to run both power and ae into the compact machines.  While inside looking at things in the terminals will go down at random intervals and then reconnect and come back up.  It seems to lose connect like it disconnected from the main line and then reconnected.  It happens quite frequently.

**Comment by Badcholo** [comment]
That seems to happen to me when i try and shift-click an inventory full of items into the me system.
I dunno what it is, but i hope it doesn't get worse.

**Comment by deathglow** [comment]
*update* it happens every 2 minutes and is down for about 5 seconds.

**Comment by XFactHD** [comment]
@Badcholo in the case you described it is definitely a power surge. Try putting some AE energy cells on your system.
@deathglow is your main base, or wherever your AE system is, chunkloaded? You could also try out what I suggested to Badcholo.

**Comment by deathglow** [comment]
The me system does have a energy cell in it and the main base has a chunk loader to keep it going at all times.  I have no issues back at my base, only inside the compact machines dimension.

**Comment by Badcholo** [comment]
yes, i only had a simple energy acceptor, a fluix cable, terminal, me drive, and storage drives.
maybe the Energy acceptor only transfers a set amount of power, i'm going to check the configs.
I'll try adding an energy cell.
I'm in the same dimension.

**Comment by XFactHD** [comment]
@Badcholo the AE system can only consume as much power as it can store.

**Comment by deathglow** [comment]
After messing with a few things I am pretty sure it is fixed.  It seems that my AE system is just to big and causes lag issues.  When I break a controller and reattach the system seems to fix itself.
