### ISSUE TITLE
Bigger machines?

### ISSUE THREAD

**Issue by SHIuSH** [thraaawn/CompactMachines#157]
32x32x32 maybe?

**Comment by XFactHD** [comment]
13*13*13 is the max size because one chunk is 16*16*16 meaning only one chunk per machine is loaded. Your suggestion would cause eight chunks to be loaded. Also, why would you need bigger machines?

**Comment by thraaawn** [comment]
What XFactHD said. Never going to happen, sry.

**Comment by Badcholo** [comment]
Do those chuncks get unloaded if the machine is broken and no one uses that chunk anymore?
