### ISSUE TITLE
Ability to destroy CompactMachines walls in Survival

### ISSUE THREAD

**Issue by Spazzze** [thraaawn/CompactMachines#158]
Hello.
I want to inform you that I was able to destroy CompactMachines walls (being inside of it), by item Vajra from Gravitation Suite mod. It is possible to break this walls using Vajra's built-in silk touch mode (it is right click to a block).

**Comment by thraaawn** [comment]
Report this to the Gravitation Suite mod. They are allowing unbreakable blocks (with a hardness of -1) to break. Not an issue of CMs.
