### ISSUE TITLE
Inventories inside Compact Machine not connecting to EnderIO Item Conduits

### ISSUE THREAD

**Issue by JEDiGamer007** [thraaawn/CompactMachines#163]
The EnderIO Inventory Panel (when outside of a Compact Machine) does not seem to connect to inventories inside of a Compact Machine, no matter in which configuration the Item Conduits are.

Is this a bug or am I doing something wrong?

**Comment by thraaawn** [comment]
You can only access the buffers from the outside. Works as intended.

**Comment by JEDIGamer** [comment]
Alright, so I have to sonehow send an item to the buffer from the inside to access it from the outside?
