### ISSUE TITLE
/setCMCoords not working

### ISSUE THREAD

**Issue by tylerspencer237** [thraaawn/CompactMachines#165]
I am using Compact Machines 1.21.

In both Singleplayer (cheats) and Multiplayer (OP), I am unable to use /setCMCoords as it returns "You do not have permission to use this command" I'm pretty sure I'm doing everything right like holding a blank CM block of the right size, and I know the id.

**Comment by thraaawn** [comment]
Are you in creative mode?

**Comment by tylerspencer237** [comment]
Yes

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
