### ISSUE TITLE
Worlds won't load, jumps to title screen

### ISSUE THREAD

**Issue by Ezekiel-Zephyr** [thraaawn/CompactMachines#166]
I'm using direwolf20 modpack and its ran fine no matter what I've added to it though theres been a brief flash of the main menu whenever I've loaded a world. After attempting to add v1.21 and finding there was a problem with another mod I went for the previous version. Now, I'm unsure as to why, my worlds won't load. Without the mod it takes longer than it did before, at least five seconds on the main menu though with it it goes past thirty and there isn't any visible progress.

**Comment by Archimedesbuho** [comment]
I'm having the same issue with FTB infinity evolved. Opening an existing world or creating a new one causes a crash to title screen/menu.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
