### ISSUE TITLE
All players disconnect randomly on a certain event

### ISSUE THREAD

**Issue by Zethalion** [thraaawn/CompactMachines#167]
My server sometimes shows this error and disconnects all players at random times:

> [04:00:01] [Thread-174/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Save@38a25548:
> java.util.ConcurrentModificationException
>         at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_45]
>         at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_45]
>         at org.dave.CompactMachines.handler.SharedStorageHandler.save(SharedStorageHandler.java:229) ~[SharedStorageHandler.class:?]
>         at org.dave.CompactMachines.handler.SharedStorageHandler.access$000(SharedStorageHandler.java:42) ~[SharedStorageHandler.class:?]
>         at org.dave.CompactMachines.handler.SharedStorageHandler$SharedStorageSaveHandler.onWorldSave(SharedStorageHandler.java:269) ~[SharedStorageHandler$SharedStorageSaveHandler.class:?]
>         at cpw.mods.fml.common.eventhandler.ASMEventHandler_353_SharedStorageSaveHandler_onWorldSave_Save.invoke(.dynamic) ~[?:?]
>         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
>         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
>         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:810) [mt.class:?]
>         at org.szernex.yabm.core.BackupTask.run(BackupTask.java:96) [BackupTask.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
> [04:00:01] [Thread-174/ERROR] [FML]: Index: 7 Listeners:
> [04:00:01] [Thread-174/ERROR] [FML]: 0: HIGHEST
> [04:00:01] [Thread-174/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@17fb98e0 onDimensionSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 2: NORMAL
> [04:00:01] [Thread-174/ERROR] [FML]: 3: ASM: cofh.core.Proxy@67849ba4 save(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 4: ASM: abo.ABO@4e546b21 save(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 5: ASM: forestry.core.EventHandlerCore@78a7be64 handleWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 6: ASM: codechicken.enderstorage.api.EnderStorageManager$EnderStorageSaveHandler@6cac44e4 onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 7: ASM: org.dave.CompactMachines.handler.SharedStorageHandler$SharedStorageSaveHandler@53075566 onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 8: ASM: noppes.npcs.controllers.ScriptController@18e5bda6 saveWorld(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 9: ASM: lib.enderwizards.sandstone.util.WorldDataHandler@50ed7da onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 10: ASM: de.ellpeck.actuallyadditions.mod.event.WorldLoadingEvents@435482f3 onSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 11: ASM: cofh.thermalexpansion.core.Proxy@1194f7fd save(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 12: ASM: li.cil.oc.common.event.ChunkloaderUpgradeHandler$@1d47af18 onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 13: ASM: li.cil.oc.common.item.Tablet$@2660a49b onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 14: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@1d361a74 onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
> [04:00:01] [Thread-174/ERROR] [FML]: 15: LOWEST
> [04:00:01] [Thread-174/ERROR] [FML]: 16: ASM: li.cil.oc.common.SaveHandler$@6b709d0e onWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
