### ISSUE TITLE
AE2 channels

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [thraaawn/CompactMachines#168]
Trying to make a compact machine with a 2 ae assemblers, each with 4 interfaces.
Dense cable links outside and inside, but connecting to it via smart cables wont let all interfaces get a channel...

Extending on this, putting patterns into the interface, then breaking the CM block does not give back the patterns

**Comment by Maxiride** [comment]
I had no troubles with AE cables, using a dense cable inside and outside the same "tap" of the compact machine, with the tap setted to Auto let me bring in\out all 32 channels.

**Comment by fusionmc-evilscoop** [comment]
perhaps...im playing dns techpack and some of the interactions in that pack can be a bit weird

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
