### ISSUE TITLE
Spectre Room glitch with Compact Machines

### ISSUE THREAD

**Issue by Maxiride** [thraaawn/CompactMachines#169]
The mods involved:[ RandomThings](https://github.com/lumien231/Random-Things) (in particular the Spectre Room) and Compact Machines.
I'm openning just one issue ticket here and link it to the RandomThings mod because I'm not sure how and which one interferes with the other one. Anyway [here](https://github.com/lumien231/Random-Things/issues/48) is the the ticket on the other repo, linking it just to do a reference.

What's happening:
If I place a compact machine inside the spectre room, enter it with the shrinking device and then get back to the spectre room, if I use the spectre key to get out of the spectre room I am teleported inside the last compact machine I entered (with nausea effect) instead of the overworld. Using the command /exitspectre also brings me back into the compact machine with nausea effects.

How to reproduce it:
1. Use the spectre key to get into the spectre room (works as expected)
2. Place down a compact machine and enter it with the shrinking device (works as expected)
3. Get out of the compact machine using again the shrinking device (works as expected)
4. Use again the spectre key to get out of the spectre dimension (**not working->brings back into the compact machine with nausea effect**)

So this is an easy way to get trapped inside the spectre room, the only way out is suicide if you have a bed outside of the spectre room otherways is an OP /tp command.

There is something that interferes with the dimension travel both in compact machines and the spectre room, or compact machine overwrites some RandomThings value or viceversa.

**Comment by lumien231** [comment]
Well it's basically my fault because i write / read the position / dimension a player entered from to general nbt tags like "oldDimension". Compact Machines changed that at some point but kept backwards compability to older versions i guess? The issue you describe is even described in the code comments.

https://github.com/thraaawn/CompactMachines/blob/804b3141256fecfbe54f5aa1772de4f4270a4e36/src/main/java/org/dave/CompactMachines/machines/tools/TeleportTools.java#L132-L146

**Comment by Maxiride** [comment]
Woah that's a quick troubleshooting!
So it's an hard thing to fix? The server I play in by the way use the  RandomThings v2.2.4 and compactmachines-1.7.10-1.21 both for MC 1.7.10 if it can help.

**Comment by IMarvinTPA** [comment]
Can we get a version of CM with an option to not use the old values so this bug can be worked around?  I'm trying to make a mod-pack that uses both of these and would like to use both spaces as limited sized safe places.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
