### ISSUE TITLE
Mobs not spawning inside the compact machines.

### ISSUE THREAD

**Issue by Fousicek** [thraaawn/CompactMachines#170]
As title says. I am on the newest version of ferret bussines and wehn i go in and want to transfer mob or place golems they disapear. 

My question is. Is ti intended or it is bug ? 

It is SMP Server.

Thx Fousicek

**Comment by Maxiride** [comment]
I had no troubles using the golden lasso from extra utilis

**Comment by xX-Gigi-Xx** [comment]
hi... i place directly mob spawner of vanilla minecraft, i use auto-spawner from minefactory reload, but mobs not spawn... and animals as cows and sheep, when i place it with Golden lasso, it disapear...

**Comment by Harkole** [comment]
Running a private server with custom mod pack.

Using MineFactory Reloaded, specifically breeder and Chrono machines to breed cows/sheep and they are being moved to another room completely which we can't access.

The Compact Machine is a Gold model and the room is split in to two levels, the bottom floor is a wheat farm 3x3 surrounded by 2 blocks water, this pipes up in to the breeder, which is then seperated by 2 blocks from the chrono. two cows breed in to the other half of the room where the spawn point was moved to so players entering are separated from the working parts and only with live stock that they can eat/kill.

I can post room layout as screen shots if it helps?

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
