### ISSUE TITLE
What happens when a CM is destroyed with a Pickaxe? And when it's put in a trash can?

### ISSUE THREAD

**Issue by Maxiride** [thraaawn/CompactMachines#171]
I made some testing about mobs inside CM - _not_ upgraded.
I found out that if I spawn some mobs into a CM and place some blocks, when I destroy the CM the blocks are returned (as expected) but the mobs not. Is it an intended behavior? Where do they go? Is the CM space destroyed also in the CM dimension so they just fall in the void?

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
