### ISSUE TITLE
Will you be upgrading this mod?

### ISSUE THREAD

**Issue by ChickenChaser99** [thraaawn/CompactMachines#172]
Are there any plans to make a 1.8/1.9 build and/or porting to / supporting sponge?

**Comment by thraaawn** [comment]
Yes. Need time and a motivation kickstart though.

**Comment by thraaawn** [comment]
Oh, and it also depends on a few other mods updating first.
Not sure whether I want to drop their support - I fear people will riot if AE2 channels are not passing through CMs anymore. Even though I really want to drop that feature anyway.

This is a bit disheartening and thus one of the main reasons why this isn't updated to 1.8 yet.
