### ISSUE TITLE
Server becomes unresponsive when joining a compact machine

### ISSUE THREAD

**Issue by dredhorse** [thraaawn/CompactMachines#173]
Hi, using unabridged u10 which has version 1.21

I had the issue yesterday that the server became unresponsive when joining a compact machine.

Unfortunately there is nothing logged on the server or in the client.

Will try to gather more info if it happens again.

Regards

Don

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
