### ISSUE TITLE
Could not use Tinker's Construct Silky Jewel as upgrade.

### ISSUE THREAD

**Issue by IMarvinTPA** [thraaawn/CompactMachines#174]
I tried to set the Silky Jewel as the upgrade item, but I do not think the item configuration can use a damage value as part of the configuration.

I tried "S:upgradeItem=TConstruct:materials:26"

If I did it wrong somehow, let me know.  Otherwise, the parameter is limited to either entire groups of items or those with no damage values.

Thanks,
IMarv

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
