### ISSUE TITLE
Unable to start world

### ISSUE THREAD

**Issue by border999** [thraaawn/CompactMachines#178]
http://pastebin.com/AhjQjKKa
Any ideas?

**Comment by XFactHD** [comment]
Your paste is invalid.

**Comment by border999** [comment]
there we go, try again

**Comment by XFactHD** [comment]
Can you reproduce this with a new world? If not, try deleting the compactmachines folder in the world's save folder.

**Comment by border999** [comment]
Seems like the issue was caused by Compact Machines default dimension selection. I would recommend that it instead select the first available dimension instead of defaulting to 3. Setting the dimension to 25 let me back in.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
