### ISSUE TITLE
"dimension already registered" everytime I launch the client

### ISSUE THREAD

**Issue by Xireka** [thraaawn/CompactMachines#180]
So, for some time now every time I launch the client and try to enter my world I can't and get the error "dimension number x is already registered", so I exit, change it in the config file and after restarting the client it works, but no matter what I set it to it gives me this error every single time I again launch the client afterwards and it's annoying because I don't know why it's doing that :(

**Comment by croziors** [comment]
is you use mystcraft it s normal or other mode you can changes dimensions in config compactmachines
change with 666 667 or other ;)

**Comment by border999** [comment]
You don't seem to really understand, It happens with EVERY dimension ID it's set to. I highly doubt making the ID stupidly high will fix this issue.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
