### ISSUE TITLE
move compactmachines

### ISSUE THREAD

**Issue by croziors** [thraaawn/CompactMachines#182]
if  i want by default all machine  ready for move and not add nether star is possible ?

**Comment by XFactHD** [comment]
No, but you can change the item needed for the CM to be moveable without loosing its contents in the config file.

**Comment by croziors** [comment]
modid:name_block_registered_with   ?? so if i want steel ingot  Railcraft's S:upgradeItem=Steel_Ingot

**Comment by croziors** [comment]
or just iron

**Comment by XFactHD** [comment]
No, you need the modid of the mod the item is from and the item's name and if needed the metadata. For example the railcraft steel ingot would most likely be railcraft:ingotSteel. You can find the item name in the language file. You can ignore the item.railcraft: part and the .name part.

**Comment by croziors** [comment]
thx S:railcraft:ingotSteel

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
