### ISSUE TITLE
[SUGGESTION] Config options for how big each tier of Compact Machines are

### ISSUE THREAD

**Issue by KoolDude214** [thraaawn/CompactMachines#184]
Would it be possible to make a config option for the size of each tier in the config file kind of like this?
`tinycompactmachinesize=3`
`smallcompactmachinesize=5`
`normalcompactmachinesize=7`
`bigcompactmachinesize=9`
`giantcompactmachinesize=11`
`maximumcompactmachinesize=13``

**Comment by XFactHD** [comment]
Most likely won't happen. The size of the biggest CM is capped at the size of 13 to really only load obe chunk per machine in the CM dimension when nobody is in the dimension.

**Comment by thraaawn** [comment]
This.
I've also started working on CompactMachines2, a rewrite of the mod for 1.10 with some major changes, there won't be another 1.7.10 version.
