### ISSUE TITLE
My game crashes if i go into a room (Compact Machine) [Worked for me by using an older Optifine version!]

### ISSUE THREAD

**Issue by Jan2220** [thraaawn/CompactMachines#185]
Hello,
If i go into a compact machine my game is crashing every time...
I´m using the Bevos Tech Pack Reborn BetaW Modpack.
Crash report:

[http://pastebin.com/M4YKP8n8](http://pastebin.com/M4YKP8n8)

I hope somebody can help me :c

**Comment by SiriusScaper** [comment]
Same issue. 
[crash-2016-07-29_19.56.17-client.txt](https://github.com/thraaawn/CompactMachines/files/391691/crash-2016-07-29_19.56.17-client.txt)

**Comment by Diresheep** [comment]
I believe this  is very nearly the same Error I've been getting, resolved by disabling optifine,  Not an ideal solution for me.

**Comment by Kpaiva** [comment]
Getting the same thing on my own custom modpack based on Infinity Evolved. It does indeed seem to be optifine. However optifine does a lot to fix some of the lag we are getting definitely not the ideal solution for us either. Hopefully this can get fixed as this mod is really cool.

**Comment by Jan2220** [comment]
Worked for my by using an older version of Optifine (im using OF 1.7.10 D4) hope its an better option for you guys!

**Comment by Zarkazm** [comment]
Can confirm.  Same crash and console errors as pasted above.  Can also confirm that downgrading Optifine from D6 to D4 fixes the issue.

**Comment by thundR** [comment]
Making sure @thraaawn knows this is still a game crashing issue.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
