### ISSUE TITLE
Empty Compact Machines lose Nether Star Upgrade

### ISSUE THREAD

**Issue by CandiceJoy** [thraaawn/CompactMachines#187]
(v1.21)

The title pretty much says it all.  If you make a compact machine, place it in the world, upgrade it, never visit it or place anything inside of it, then break it, the machine is un-upgraded and you've lost your nether star.  I seriously thought something was changed where the nether star is lost after 1 break until I realised it works fine...if there's already things inside the CM.

**Comment by XFactHD** [comment]
The fact that the Compact Machine accepts the nether star when it was never visited looks like a bug to me. That the Compact Machine looses the upgrade when it is broken without having been visited makes sense because the Machine hasn't been generated in the CM dimension.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
