### ISSUE TITLE
StackOverflow shift-clicking items in any GUI from CM

### ISSUE THREAD

**Issue by Eufranio** [thraaawn/CompactMachines#188]
Same as https://github.com/thraaawn/CompactMachines/issues/31, re-opening because it still present.

**Steps to reproduce:**

1. Place down any CM block with GUI
2. Open the block
3. Shift-click any item in your inventory. Boom, crash.

Crash-report: http://hastebin.com/itavimujev.coffeescript

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
