### ISSUE TITLE
ae2 connection not working - incompat with rv3-beta 6?

### ISSUE THREAD

**Issue by DoomSquirter** [thraaawn/CompactMachines#189]
playing unabridged, single player.  
appliedenergistics2-rv3-beta-6
compactmachines-1.7.10-1.21

no events thrown in log.
main base is chunkloaded via chickenchunks.  
connected from base controller -> cable -> east side of cm (huge size, with star applied)
inside, east side of cm, any cable + crafting terminal, can't see main ae system.  

is this version of ae incompatible with the cm version?

I just did something similar in another pack (the best of both worlds or something, can't rem name) and this exact setup worked fine there.  
that set of mods (where it worked) are:
appliedenergistics2-rv3-beta-5
compactmachines-1.7.10-1.21

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
