### ISSUE TITLE
Upgrade to 1.10+?

### ISSUE THREAD

**Issue by Nuinethir** [thraaawn/CompactMachines#191]
Really enjoyed this mod in 1.7.10, would love to see it ported to 1.10 and up. A lot of modders are making the move, and just recently COFH announced they too are upgrading. Any chance this might get the same treatment? Thanks! :)

**Comment by Maxiride** [comment]
+1, 1.10.2 seems to be new "milestone" for a while. Subscribing the issue to receive news about it! =)

**Comment by Maxiride** [comment]
Just randomly found [this](https://github.com/thraaawn/CompactMachines/issues/184#issuecomment-230786832) comment from #184 . But can't find any other news even tho several months passed.

**Comment by DeadSix27** [comment]
@thraaawn any news for us? Really loved this mod

**Comment by thraaawn** [comment]
Started working on it again. I'm hopeful to get some more things done this week. I got the basics (cube generation, player teleportation etc). Other things are still in the planning phase (e.g. how to power the machines).

No real dependencies, especially as I'm starting from scratch.

**Comment by NerdCraft** [comment]
any prevision?

**Comment by DeadSix27** [comment]
@thraaawn Awesome! If you need a tester :) say so I'll gladly test it!

**Comment by thraaawn** [comment]
There is still lots missing (interfaces, energy consumption, upgradeable machines and machine upgrades, cosmetics, testing), but I'll probably release feature incomplete alpha versions every now and then. My goal for a first alpha is this weekend. Absolutely no promises though.

**Comment by DeadSix27** [comment]
@thraaawn ah, that answers my previous post heh, you replied right when I hit "comment". Looking forward to that!

**Comment by thraaawn** [comment]
Progress! Thought I keep you updated.

~~Interfaces~~, now called Tunnels are implemented for Capability based systems (i.e. fluids, items, energy and whatever other mods add) and can be mapped to wall tiles freely, i.e. any wall tile can be mapped to any external side, but each external side only once.

Next up: chunk loading and groundwork for upgradeable machines, e.g. small -> giant without losing the interior. Then energy consumption, items and recipes. Then alpha.

**Comment by DeadSix27** [comment]
Awesome! thanks for keeping us up to date @thraaawn, is Mekanism Gas capability based? EnderIO has Gas Conduits when Mekanism is installed, would be cool to have them work inside the CM's too.

**Comment by thraaawn** [comment]
Looks like Mekanism is capability based: https://github.com/aidancbrady/Mekanism/blob/333cc7f/src/main/java/mekanism/common/capabilities/Capabilities.java#L43
I have not tried it though.

**Comment by DeadSix27** [comment]
Well, I'll test that as soon as I can :) 
You do a full rewrite right? If so, in that case, one more thing .. bigger rooms, will they be a thing in the future maybe,hopefully :P? (Feels like now is the time to ask)

**Comment by thraaawn** [comment]
Nope. Same chunk size -> same room size.

**Comment by DeadSix27** [comment]
Aww :P well worth asking

**Comment by DeadSix27** [comment]
@thraaawn *cough*
![image](https://cloud.githubusercontent.com/assets/1492505/23363480/17abaf66-fcfb-11e6-9e4a-6f9c41337d2c.png) :P

**Comment by thraaawn** [comment]
Sorry :(

**Comment by thraaawn** [comment]
I've added a project board to keep track of things still needed to be done before I can release something worth testing. It might also hint at some new functionality and stuff :)

**Comment by DeadSix27** [comment]
For the people that do not know what he means: It's here: https://github.com/thraaawn/CompactMachines/projects/1

**Comment by thraaawn** [comment]
Doesn't look like that's possible :poop: feel free to comment/ask in here.

**Comment by Nuinethir** [comment]
@thraaawn   Will Compact Machines support Refined Storage (AE2 successor)? I know it is somewhat cheaty in terms of routing storage from one area to another (I believe you had an option in the configs previously to disable AE2 usage), but I am not a hardcore player and would prefer the functionality.

**Comment by DeadSix27** [comment]
I was about to mention that too, keeping AE and possibly add RS support, but figured its a little too early to ask that.

**Comment by thraaawn** [comment]
Probably not, as RS is currently not using [forge capabilities](http://mcforge.readthedocs.io/en/latest/datastorage/capabilities/) on their network nodes to determine neighboring blocks, but classic java interfaces. It's also a lot easier and cheaper to set up network transmitters with Refined Storage than it is in AE2 and it only takes up one block space. So the effort of having to maintain *custom* mod code is not really worth it in this case, i think.

💭 changing rs to use capabilities would arguably be the better solution, but also a rather invasive change on their end.

**Comment by Nuinethir** [comment]
@thraaawn Hey, no problem, thanks for the explanation. I had planned on using the Network Transmitters, but just liked the idea of utilizing CM for the entanglement. Still, looking forward to this great mod. :)

**Comment by DeadSix27** [comment]
@thraaawn about the tree sap, afaik ThermalEX/Found, will have some kinda "tree sucker" in 1.10, i played around with it.
Or you could use the oreRubber type of stuff, like IC2/Techreborn and previously MFR.
Other possibilities could be a mixture kind of type, e.g rubber + water in a CompactMachines added machine could turn into some kind of "shrinking oil" (RF/Tesla/FE/etc + water + rubber)

**Comment by thraaawn** [comment]
@DeadSix27, the fluid is already fully implemented (incl. custom flow physics and miniaturizing living entities on touch), just need a way for players to mass produce it. Currently trending towards this:
 - find a pool of miniaturization fluid somewhere,
 - place/push an animal/mob into it so it gets shrunk,
 - make it dead while its miniaturized.
 - There's a certain chance that it will drop an item, maybe some sort of gland, that can be combined with a bucket of water (or sth else) to make miniaturization fluid.

You will need it to a) power your PSD (currently thinking 100mb per enter/exit operation), b) to craft different items by pouring it over multiblocks (e.g. to craft a tiny CM you'd build a 5x5x5 cube from Machine Wall blocks, then pour the fluid over it and trigger the crafting by throwing some sort of catalyst into the fluid). But you can also use it to shrink yourself for a limited time using either a pool of the stuff sitting somewhere or by brewing potions with it.

**Comment by Ristellise** [comment]
i wanna post here that i miss this mod for 1.10... also Opencomputers... it is gonna be kinda difficult to implement this but i think it is possible.

**Comment by davenonymous** [comment]
@Nuinethir, oh, just saw that refined storage for mc 1.11 is using forge capabilities for their network nodes. Once I ported this mod to the newer version (first want to get a stable 1.10.2) it should work out of the box.

**Comment by DeadSix27** [comment]
@thraaawn thought about using things like: https://minecraft.curseforge.com/projects/compatlayer ?
To get the mod working on both, 1.10 and 1.11 at the same time? Mcj does that with all his major mods I think, could be a good idea.

EDIT: http://wiki.mcjty.eu/modding/index.php?title=CompatLayer-1.11

**Comment by davenonymous** [comment]
Yupp, will most likely be using it.

**Comment by davenonymous** [comment]
The travis builds are now being uploaded to dropbox [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0), you'll want the latest cm2-2.0.0-bXXX.jar package.

These are rather early -not even alpha- builds with probably lots of bugs, e.g. there are issues with enderio conduits not handling capabilities properly and you might get shrinked and never returned to your original size. Bug reports are very welcome, thanks for your help! But do not use these builds in worlds without a backup!

**Comment by AndreiTS** [comment]
It seems safe :D

**Comment by davenonymous** [comment]
It should be rather safe to use the mod now. Still: please make backups of your worlds.
ANY feedback on the current [builds](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0) (>= b87) is very appreciated. I need to know as many of the bugs and issues as possible to fix them before being able to release a beta on curse.
Thanks for your help!

**Comment by AndreiTS** [comment]
I still don't knowm how to craft the blocks.... .-. (using minetweaker for now)

**Comment by davenonymous** [comment]
An example: Take 9 Iron Blocks and place them 3x1x3 flat on the ground. Take 4 buckets of miniaturization fluid and cover all of the iron blocks with it (i.e. place one bucket in each corner). Throw a piece of Redstone Dust on top of the 9 iron blocks, into the fluid.
You should get Machine Walls for it, no?

**Comment by AndreiTS** [comment]
Yes, it worked (I didn't know abou the redstone, you should say this is the jei recipe)

**Comment by AndreiTS** [comment]
Another question: How do I get miniaturization fluid?

**Comment by davenonymous** [comment]
Redstone is now being mentioned in the JEI recipe.
The PSD serves as a book for documentation now, it says about Miniaturization Fluid: You can obtain it by either searching for old broken machines found in the overworld or by killing entities that are under the effects of the miniaturization fluid.

So basically: to get large quantities you will want to build a mobfarm and shrink them before they are being killed.

**Comment by AndreiTS** [comment]
I added cm2 to a generated world, so I didn't find any other machine, it's hard to find it?

**Comment by davenonymous** [comment]
The chance for a broken machine to spawn in the world can be tweaked in the config file, by default it's at a low 0.05% chance per chunk. There is no retrogen.

**Comment by Saereth** [comment]
Do you intend to add an alpha build to curse for pack inclusion by chance? I understand this is an early build but we would like to use it and help test and get you curse credit as well if possible.

**Comment by davenonymous** [comment]
If I understand curse correctly alpha builds wont sync to the curse app to begin with even when uploaded to curse 😞.

**Comment by Saereth** [comment]
They dont automatically propogate and mark for as latest for people to manually update, however if packs have your mod added they will work and sync with those pack downloads np.

**Comment by davenonymous** [comment]
Oh, did not know that. Will upload the current build manually now and automate it soon. Thanks for the info!
Edit: Done and approved. Enjoy!

**Comment by Drakkar666** [comment]
While I'm not sure if that's just my screen issue, which occurs whenever I boot my PC, as of now Compact Machines 2.0.0-b98 together with More Player Models for 1.10 causes weird flickering wave on my screen, this occurs only when you make your player model taller or shorter. It works fine with normal player height.

**Comment by davenonymous** [comment]
Since we have alpha builds on curse now etc, i'll close this issue.
Please open a new one for each issue you encounter. Thank you!
