### ISSUE TITLE
Client crashing on join after game crashed in broken compact machine block

### ISSUE THREAD

**Issue by orbitwar** [thraaawn/CompactMachines#192]
I own a small server in which I let my friend play on at their leisure. Today, I was on with one of them and we were messing around with compact machine blocks because they seemed like a cool idea. To test their capabilities, my friend went inside of a compact machine then I broke the block and everything seemed to be fine until a few seconds later, my friend's game crashed. I tried to solve it by deleting the files of the compact machine dimension (on the server/host) to make the server respawn him in the overworld... to no avail. So I reverted it and put the files back. Now, my friend can't join because each time he joins, his game crashes the instant he is in the game. His error log is attached below.
http://pastebin.com/vxCpNi8c

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
