### ISSUE TITLE
Allow Camouflaging blocks

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#40]
i.e. make them look like a redstone furnace or sth else

**Comment by Surrogard** [comment]
How about something like the [Conduit Facade in EnderIO](http://wiki.enderio.com/Conduit_Facade).
These are pretty nifty and can be anything one wants. If you don't want an extra machine for painting you could use shapeless crafting for example...

**Comment by thraaawn** [comment]
It will be more like drawbridges with a slot for the block used as camouflage.

**Comment by Surrogard** [comment]
Or like that. Haven't used drawbridges since now so I didn't know they could do that. :)

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
