### ISSUE TITLE
Power Requirement for Entering/Exiting

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#44]
Not sure whether i want this yet or not.

**Comment by Badcholo** [comment]
Power requirement is not needed. I think it would get annoying trying to get into the machines while setting them up.

**Comment by thraaawn** [comment]
I will probably use another block to power it, similiar to the QED.

**Comment by Badcholo** [comment]
I think this is going to cause problems, what happens if you run out of power and your inside? Can you power it from the inside? Another block to place next to each machine? Rable Rable Rable Just kidding.

**Comment by pip69** [comment]
Just some thoughts on this topic;
 - enter/exit should not need energy when using PSD
 - costs to transfer
 - costs for options & upgrades 
      - enter/exit without PSD
      - light levels
      - mob spawns
      - individual biomes
      - chunk loading
      - quantum entanglement without needing nether star
      - spawn protection
 - config options for it all

**Comment by thraaawn** [comment]
@pip69 i agree with all of this.

additionally:
* needs a way so CMs can not get powered from the inside, which means custom power system, probably qed like
* creative upgrades need to exist as well, mostly for modpack makers

**Comment by Badcholo** [comment]
Technically the PSD is what should use power if any. Not the CM. As i understand the CM is just a open spaced block that you shrink yourself and items into.

**Comment by davenonymous** [comment]
This is implemented using Miniaturization Fluid.
