### ISSUE TITLE
AE2 Compatibility Issue - Dedicated Server

### ISSUE THREAD

**Issue by psychofad** [thraaawn/CompactMachines#60]
Ok, I have created 6 max size compact machines, upgraded them all with a Nether Star, and Quantum Entangled them all to Machine # 0.  Inside machine # 0 I have simply connected Dense Fluix cable from all access points and the cable connects in the center of the room.  1 of the blocks is then placed near my ME Controller and a Dense Fluix cable is ran into one of it's faces.  This allows me to place any of the other 5 machines down where I want there to be access to my ME network and simply run cable off of any face of the block to displays, interfaces, P2P interfaces, etc.  

The problems I am having are:
1) Any time I restart my server, the channels will no longer connect through the block...I have to break the block that is located near my controller and place it even just 1 block over on the x or y coords then reconnect the Dense Fluix cable ran to it to get it reconnect the channels. 
2) If I place anymore of the Entangled CM's and then break them the channels will cease to connect through the block near my controller until I place the additional Entangled CM down again or break the block that is located near my controller and place it even just 1 block over on the x or y coords then reconnect the Dense Fluix cable ran to it. 
3) Sometimes when trying to run ME cable into the CM some faces of the machine work while others do not, so I can run the cable into South, West, and East but North would not connect to anything inside the block.  And I don't think I have yet to get the bottom of the block to ever work with ME cables...to be clear the cables connect to the block, but the channels will never transfer through.

There are no errors showing up in the log that I can find for this...just the problems listed above which are a bit annoying.  I have not tried the latest build of compact machines, but decided to post this issue as this was not mentioned in the changelog for it nor could I find any of these bugs reported on this Github.

Using:
appliedenergistics2-rv1-stable-1
compactmachines-1.7.10-1.12

Feel free to contact me if you need additional info about my modpack or the problems listed above.

Thanks,
PsychoFad

**Comment by Skar78** [comment]
I may have a related issue:

Giant compact maschine, using dense cable to contact directly into the ME controller.

This setup did not work straight away. after trying different cables and settings, out of pure desperation I simply restarted minecraft with the settings shown below - and it suddenly worked.

http://imgur.com/a/N1CsQ?

Kind of odd, but I really did do no change whatsoever after restart.

This was also not jsut visual, as my setup inside of the compact maschine are automated inscribers and their ME interface recipe did not show up in the ME network till I restarted.
