### ISSUE TITLE
Internal server error when entering compact machine

### ISSUE THREAD

**Issue by jlove87** [thraaawn/CompactMachines#62]
Last night when entering a compact machine I received an Internal Server Error message.  Upon rejoining the server, I noticed that I was in the compact machines world, but not in a compact machine.  From there I started falling to my death as I was just somewhere randomly in the world nowhere near the machines boundaries.  Luckily I could fly, but still almost died from the void damage (was -200-ish down).

Can we get a check in place when a client joins the server and are in the compact machine world to see if they are within the machine boundaries?  If they are not within the boundaries, I believe they should either be moved to one of the machines, or sent back to wherever they originally came from.

**Comment by thraaawn** [comment]
This can only happen the first time a player enters the dimension and a crash at the same time is pretty rare. Won't fix unless it pops up again.
