### ISSUE TITLE
IC2 Power

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#7]
It's not sided, though. Make an exception and give all sides the same buffer?
Not sure yet.

**Comment by sneakin** [comment]
That's close to what I did here https://github.com/sneakin/CompactMachines/tree/ic2 where the outgoing buffer is shared. Not quite sure if this is pull request ready, but I'd love some testing.

**Comment by thraaawn** [comment]
Interesting. I actually did this for Botania already, so IC2 doing the same thing, why not.
Reopened issue so I'll investigate this once I got some time to do work on CM.

**Comment by sneakin** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On October 20, 2015 10:11:35 AM EDT, thraaawn <notifications@github.com> wrote:
>Interesting. I actually did this for Botania already, so IC2 doing the
>same thing, why not.
>Reopened issue so I'll investigate this once I got some time to do work
>on CM.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/thraaawn/CompactMachines/issues/7#issuecomment-149580078

I'm considering using either transformer upgrades or inserted wires as a way to gamify the EU rate. There's some refactoring that's need w/ hoppingmode storage that's apparent in my latest commits.
- ---
Owner, SemanticGap
http://semanticgap.com/
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJFBAEBCgAvBQJWKQcnKBxOb2xhbiBFYWtpbnMgKHBob25lKSA8bm9sYW5AZWFr
aW5zLm5ldD4ACgkQ697vgoNCIrEEXQ//V/7QraPfl9/nLwlRV4f14V2c2Tn9Qhe8
7MO9z/5z+X984k33NPfyZv4Qfru3FSzJWAqn3nC15GbbwbXPb1sBjsDk7iqWUG1b
0d57wN2J91TNjOphz75viHTP36pL5lZXxZKTX5R+CjQjT5weUcvW6IUlwnfUOHIZ
1E7qjfi58xpM37gn66XBC/HGC/TaFU8TDTzRzf7UMKPVlFmVEExekxAjByzEFEWe
joxOQgO5Kvl2nG2wGu4qQshhrUm291dI1YbovgkmhF517rVInMueLmLl9nd6MV6P
qwhzM14uhIKqNMVIDcZBljXXPByIi3FPk5vvL4aZDju6CYd2TpIVEufd7k9+UMq3
RFIrEQtO0ZYjr1pmH7nw+B5jH1JRucDcNgGaO9dOkOCllX4+aZqN2TDnAj9fA9LO
vB6JW0VcHBehy25hIO2+G7B9KBzaGUoH9n1eoEFA/fOsqmKDyLyhDyml0QiKtZuX
wE5+eSCRw0+uVLsD0qILDpF4gm/gVTVwryh8h0q/pW8DOw/8Ehwrf9kDXw3HrG0/
Di2FOH2sGd5n4aP61B0Y1269XzanwTqjxP9cB3bKBdUArZPwoSJERjmXCHDJ6koL
NTt8ljJCbURalE1nMEtN7ZehZYjUSqXF7kOaKt79tlMVir13l/Lho7R/yKwMFACO
9MTgdzw/uwI=
=mfpu
-----END PGP SIGNATURE-----

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Comment by sneakin** [comment]
Can't wait. Was about to try to emulate this with OpenComputers.


-------- Original Message --------
