### ISSUE TITLE
Item Dupe bug w/ Extra Utilities

### ISSUE THREAD

**Issue by UkeFox** [thraaawn/CompactMachines#71]
Just installed this to my server and I noticed that when I place an item from Extra Utilities then leave the machine dim, I get two copies of the item. I tried it with items from other mods...  but it seems to only affect Extra Utilities. 

--------Edit---------

Seems like it only affects things like barrels and generators. I haven't seen it dupe other things.

**Comment by thraaawn** [comment]
How to reproduce:
1. Place some sort of Extra Utilities Generator in the CM block
2. Leave the CM and break it with a pickaxe.
3. You'll have two generators.
