### ISSUE TITLE
Not always working with Smart cables from Applied Energistics 2

### ISSUE THREAD

**Issue by Gidmark** [thraaawn/CompactMachines#77]
I try to connect a side with a smart cable from Applied Energistics and inside the machine add an interface block which should provide some blocks for the machine to work with. I got it to work one time, but now i can't get it to work again. I'm running the mod through Modsauce, might it be something with the pack?

**Comment by thraaawn** [comment]
You have given very little information for me to be able to help you. It should work and it does work when I test it.
Please provide the steps necessary to reproduce this in a newly created world.

**Comment by Gidmark** [comment]
Sorry, i'm using compactmachines-1.7.10-1.13 and appliedenergistics2-rv2-beta-7. It seems to work when i restarted the server. What more info would you like?

**Comment by thraaawn** [comment]
You are using a very outdated version. Several AE2 issues have been fixed since 1.13
Please update and try again.
