### ISSUE TITLE
[1.17] AE Server crash on startup when CM Adjacent to CPU, but not always.

### ISSUE THREAD

**Issue by Fogger** [thraaawn/CompactMachines#79]
I started this report on the AE tracker: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/879 since the error specifically mentioned AE, but eventually came to the realisation that it was the CompactMachines adjacent to the CPU causing the crash: http://hastebin.com/aliwapudod.1c
![Where it used to be](http://i.imgur.com/tbSnKEc.png)
Even though they have been like this for weeks without any issues. suddenly one day, the server repeatedly crashes on boot until I removed the outlined CPU in MCEdit.

**Comment by nister6000** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/835

The same crash btw.

**Comment by thraaawn** [comment]
I will look into it and try to reproduce. Thanks for the report.

**Comment by Omeryl** [comment]
Have a similar problem as well. Actually, probably almost exactly the same issue.

**Comment by Saereth** [comment]
we're having a similar issue, I tried with the box connected directly to the controller and also with a dense cable from the controller to the box. Doesnt do it right away, this box was connected for about 2 days, but eventually; [17:00:39] [Server thread/INFO]: Connection already exists between node at [dimension=0, x=-1222, y=77, z=-369] and node at [dimension=0, x=-1222, y=76, z=-369]. Server went into crashloop with that until I removed the dense cable. hooking it back up doesnt immediately crash again but inevitably it does eventually.

**Comment by downslope7** [comment]
I run the server Saereth plays on and we had a hell of a time finding the offending blocks in the world with the default crash exception message. If you're stuck with a corrupt world and don't want to remove CM, I issued a pull request upstream to AE2 to add some additional logging information above.

You should be able to cherry-pick [this commit](https://github.com/downslope7/Applied-Energistics-2/commit/30191eb5bac39ee66e775219c38564273c5d7558) on top of whatever beta of rv2 you're using and have it compile cleanly.

**Comment by downslope7** [comment]
This is also the issue I was referencing on IRC which is now #86 -- I'm not so certain chunk loading has anything to do with the cause of the problem anymore.

**Comment by Saereth** [comment]
I would also add that this never happened before the latest update to AE2, so I have a feeling something on their end broke things

**Comment by Saereth** [comment]
We havent run into this issue at all since updating,

**Comment by thraaawn** [comment]
@Saereth, so you're running 1.18-pre without issues? I might release 1.18 early then.

**Comment by Saereth** [comment]
yes we even attempted to force the issue, connected up cables to every face of multipe CMs inside and outside, about 30 of them, some direct to controllers, some to dense cables and restarted the server several times we could not get it to crash at all.

**Comment by thraaawn** [comment]
Neat, this is very good news. Thanks for the support!

**Comment by thraaawn** [comment]
Released 1.18 which is a rebranded 1.18-pre.
Assuming this issue is resolved, if not: please reopen.
