### ISSUE TITLE
Client Crash when entering machine

### ISSUE THREAD

**Issue by NonniT** [thraaawn/CompactMachines#80]
Hi,

I've been experiencing client crashes every time I attempt to enter a machine. It happens regardless of if I've connected anything to the machine or not - no issues on that front, but even a completely unconnected machine will cause a crash. Due to references to dimensions and so on in the crash reports I tried changing which dimension is utilised by Compact Machines (in both the server and client config files, as I thought there may be some form of conflict), but this didn't result in any change in behaviour. No idea if it's me doing something terrible or a bug, but happy to give any further information if you want it.

This is with version 1.17 :)

Full crash report:
http://pastebin.com/Ytc9a7hZ

**Comment by NPException42** [comment]
I would take a wild guess and put the fault on MystCraft. At least that is what the crash report suggests to me. I could bet that if you remove MystCraft, it would be fine. ^^

**Comment by NonniT** [comment]
Yeah, I'd suspected Mystcraft but with people having used both on the same versions seemingly without issues, I was hoping it wasn't :(

Confirmed that removing Mystcraft worked; can enter and leave compact machines without issues now.

**Comment by NPException42** [comment]
I suggest you open an issue in the [Mystcraft issue tracker](https://github.com/XCompWiz/Mystcraft-Issues/issues) with a link to this issue.

I'm still curious if @thraaawn could do anything about the problem from his side.

**Comment by thraaawn** [comment]
It looks more like an issue with [NotEnoughResources](https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/compatibility/mystcraft/MystCompat.java#L14) doing some dimension checks when mystcraft is installed, but not able to handle the cm dimension because it has no provider? @way2muchnoise @hilburn

**Comment by way2muchnoise** [comment]
@NonniT @thraaawn You should update NER to the [latest dev build](http://jenkins.jakimfett.com/job/NotEnoughResources/) I fixed this already

**Comment by thraaawn** [comment]
Thanks for being awesome @way2muchnoise
