### ISSUE TITLE
Adapt inside biomes to the outside CM

### ISSUE THREAD

**Issue by shivachirr** [thraaawn/CompactMachines#83]
so im trying to make a rotary craft farm and the machinces read way to low tempaurtures around -108 c if this is the case then other temp senstive mods and blocks may also be effected like big reactors or mariculture. i have not fully tested this out but its possiable other mods will be hindered other than just rotarycraft

**Comment by NPException42** [comment]
How do you read the temperature of a CM? With some debug Item?

**Comment by shivachirr** [comment]
i read the machine though wailia and it said the machine temp was -108c cold just placed

**Comment by NPException42** [comment]
I cannot speak for CM officially, but to me it looks like that value is somehow calculated by RotaryCraft or DragonAPI using the biome temperature at a specific location.

Further investigation has to be done by @thraaawn, I just tried to find the general direction to look for the problem. ^^

**Comment by thraaawn** [comment]
I don't really understand this problem. What exactly does RotaryCraft do and how does it come up with arbitrary temperatures? What makes you think this is a CM issue and not a RotaryCraft one?

I'm a bit confused here. Also: just to be sure, you are talking about the outside Compact Machine block when you say "i read the machine though wailia", right? Not the walls on the inside.

**Comment by MrabEzreb** [comment]
I think that what is happining is that the biome temp of the compact machines dimension is really low

**Comment by thraaawn** [comment]
That actually makes sense. We're talking about the temperature on the *inside* of the machine. That wasn't really clear.
The CM world is using the sky biome, which is [-100°C for rotarycraft](https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries%2FWorld%2FReikaBiomeHelper.java#L271).

Not sure whether I will change this and why exactly I used the sky biome.
-> Issue is on hold for the moment.

**Comment by MrabEzreb** [comment]
alright, this is actually pretty important for me too, but I never got far enough with rotarycraft for it to matter :P

**Comment by pdgwien** [comment]
It would be really awesome if you could change the biome to something, where we can use RotaryCraft machines. Even with Lava I cannot get my Steam Engine over 87°C (which is too little).

**Comment by shivachirr** [comment]
that what i was trying to do i was hoping to make a lube farm and processing using steam engins but you know what happened

**Comment by pdgwien** [comment]
I solved it for myself by just forking it and changing the involved codes. I noticed no side effects of doing so.

**Comment by shivachirr** [comment]
mind saying how

**Comment by pdgwien** [comment]
1. Find involved code.
2. Change code from first step.
3. Build mod.
4. Profit.

**Comment by NPException42** [comment]
You could make a pull request with your changes, @pdgwien. Maybe @thraaawn takes your changes.

**Comment by theron61** [comment]
My preference is to keep or select to keep the existing behavior.  The Sky biome is a very good choice for ReactorCraft stability.  RotaryCraft engines that do not rely on ambient temperature like the steam engine will work fine.  BTW - BuildCraft Oil through the RC Liquid Distillery is a very good source of lubricant when used with oily, distilled or refined bees.

**Comment by Saereth** [comment]
If there was a biome selection tool it would be pretty sweet, maybe an upgrade for the CM similar to the nether star ugprade?
