### ISSUE TITLE
Can't right-click with Personal Shrinking Device

### ISSUE THREAD

**Issue by plazia** [thraaawn/CompactMachines#84]
I can get inside my compact machine by right clicking with the device. However when I try to exit the machine by right clicking the device anywhere on the walls or whatever nothing happens. I cannot escape the confines of the device. I have to /cofh tpx playername x y z dim. to get back.

I'm not sure if it is another mod I'm running interfering with this but I can get to other dimensions like the spectre dimension from Random Things fine. Also the nether works OK.

**Comment by MrabEzreb** [comment]
have you tried to right click the PSD into the air, instead of on the walls? Might be causing an issue

**Comment by plazia** [comment]
Yeah I'm trying in the air (not directly at a block) and also at the walls but to no avail.

**Comment by MrabEzreb** [comment]
huh, not sure what's causing that. I guess Thraawn will have to look into it, I might be able to as well :P

**Comment by thraaawn** [comment]
Well, there is not much I can do without being able to reproduce the issue.
A few questions:
* Can you set the spawnpoint of the CM?
* Does it say so in chat and does it actually work?

**Comment by plazia** [comment]
Modpack: Resonant Rise 3.2.4.0
Compact Machines version: COMPACTMACHINES-1.7.10-1.17.jar
Nothing is echoed or output to chat.
I simply enter the compact machine and I can't get out of it.

Update - It seems to be fixed now. Perhaps it's something my end. I am running an inordinately large number of mods. I'll keep you posted if it occurs again and if I'm able to how to duplicate it.

**Comment by thraaawn** [comment]
Not reproducible and resolved.
