### ISSUE TITLE
Mekanism cardboard box can be used to break unbreakable walls inside machines

### ISSUE THREAD

**Issue by Kazzamkablam** [thraaawn/CompactMachines#85]
step 1: make cardboard box
step 2: use cardboard box on unbreakable wall
step 3: ???
step 4: profit!

**Comment by thraaawn** [comment]
It looks like Mekanism is allowing blocks with a hardness of -1 (== unbreakable) to be picked up with the cardboard boxes. See forges Block.setBlockUnbreakable(). @aidancbrady, is this intended behavior? If so I can add the exception manually via the API, but it looks more like a bug as it allows you to break blocks which should be unbreakable.

**Comment by thraaawn** [comment]
I've opened a corresponding issue on the Mekanism repository:
https://github.com/aidancbrady/Mekanism/issues/2219

**Comment by thraaawn** [comment]
Fixed in v8 of Mekanism.
