### ISSUE TITLE
Logistics pipe network does not cross the machine interface

### ISSUE THREAD

**Issue by ltouroumov** [thraaawn/CompactMachines#88]
Putting either a basic logistics pipe or a standard pipe in the interface in auto mode does not allow the logistics network to cross the interface.

**Comment by thraaawn** [comment]
Not going to support logistics pipes, sorry.

**Comment by XFactHD** [comment]
If you have AE2 installed, you can put a ME cable in the CM interface and put an ME interface on the outside and on the inside of the CM and then some logistics pipes on the ME interfaces. Which pipes you need to use is written on the AE2 wiki.
