### ISSUE TITLE
Removal of AE2 support.

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#90]
Leaning towards it at the moment.

a) It's very OP.
b) It removes need for entangled states etc
c) It's the most buggy feature this mod ever had.

**Comment by Saereth** [comment]
We actually just disallowed entangling on our server to bypass quantum bridges, the ae2 connectivity in general though is a huge draw to the mod, would be sad to see it go.

**Comment by downslope7** [comment]
Huge vote no for this if possible, it's my favorite part of the mod.

**Comment by NPException42** [comment]
I wonder how removing AE2 would remove the need for entangled states?

Wouldn't just removing entanglement make things so much easier for you?

**Comment by mcgraj3** [comment]
I vote no. The ability to disable entanglement already solves the problem in my opinion. If a server owner doesn't know how to disable it, I hate to think what else is wrong with their server. Besides, building a Quantum Bridge is not exactly difficult.

**Comment by eduardog3000** [comment]
If anything, don't remove support, make it a config option (and default it to not supporting AE if you want).

**Comment by psychofad** [comment]
Yeah Seriously....My entire autocrafting setup is inside one of the compact machines...please don't make me have to move it all. :P

**Comment by thraaawn** [comment]
ok, i'll keep it.
