### ISSUE TITLE
Re-aligning machine outputs

### ISSUE THREAD

**Issue by mtrevor** [thraaawn/CompactMachines#91]
When placed, machines are always aligned the same way: north will always be the same direction etc. This makes portable machines tricky to move and install in various locations unless the orientation is identical in each place.

A simple solution would be a tool similar to the wrench in many mods which allows for rotating the machine through all possible orientations.

A more advanced one could be the provision of a "patch bay" style model, allowing for custom linking between the external and internal ports. This would be especially handy if it allowed for multiple mappings eg the north & east face both input to the north face, or having internal north output to east & west (with the option of round robining the outputs).

**Comment by thraaawn** [comment]
Interesting. I'll think about it, but this is basically already possible: just put a CM inside of a CM and rewire in the outer CM how you desire. Would obviously add a bit of delay and material cost.

**Comment by mtrevor** [comment]
That's a brilliant idea, and obvious in hindsight. Cheers!
