### ISSUE TITLE
Mekanism 8 gas tube to input crashes the server

### ISSUE THREAD

**Issue by ReneM** [thraaawn/CompactMachines#94]
Connecting a Mekanism 8 Pressurized tube (gas conduit) carrying any gas to a Compact Machines input crashes the server (and corrupts the world, until the connecting block is deleted).

Crash report: http://pastebin.com/Pyqq5PYS

**Comment by draeath** [comment]
There were a bunch of API updates between Mekanism 7 and 8... that is -probably- what happened, here.

So, I'm not much of a coder so this should be taken as my flailing about uselessly, but this -might- have been fixed on Mekanism's end (in dev at least, commit was 2 weeks ago). The Mekanism dev has been adding compatibility code here and there, but ideally the new APIs would be used instead. Here's the commit on their end: /aidancbrady/Mekanism/commit/0064f09d8c03074806f07392f131e4feab44d7fa

**Comment by draeath** [comment]
See #89 - has this commit made it into a build yet? We're using 1.17 (which is what you've got on Curse)

**Comment by thraaawn** [comment]
I will release it later today. Cheers.

**Comment by thraaawn** [comment]
Done.

**Comment by ReneM** [comment]
Fantastic, thanks :)
