### ISSUE TITLE
[enhancement] wrench "magic"

### ISSUE THREAD

**Issue by Tcll** [thraaawn/CompactMachines#96]
this mod is cool and all, but I'm usually one to build my "machine" first, then install it where needed.

being able to move the block after building inside it would really help when you don't have enough inventory space for everythig inside.

what am I thinking exactly?
the wrenched block will retain it's link and will not stack on unlinked or other linked blocks.
similar to how extra util generators retain their power after being broken.

also, R-clicking a side of the block with a wrench should rotate the contents of the block.
similar to how a redstone furnace or other machines can be rotated

don't get me wrong, I like the idea of breaking the block with a pick to return the contents of the block :)
but shift-R-clicking the block with a wrench should just allow you to move the block. ;)
perhaps even introducing your own wrench would be better to help keep things solid ;)

**Comment by thraaawn** [comment]
You can upgrade CMs with a Nether Star to be able to move them however you wish.

**Comment by Tcll** [comment]
wasn't explained... sorry for the inconvenience
