### ISSUE TITLE
Large CM + AE2 dense cable --> crash

### ISSUE THREAD

**Issue by XFactHD** [thraaawn/CompactMachines#97]
If I place a ME dense cable next to a large compact machine, I get a abstractMethod error:
Crashreport: http://pastebin.com/VhwvD4pV
CM version: 1.7.10-1.2
AE2 version rv2 beta 14

I have also submited an issue on the AE2 issue tracker.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1254

**Comment by thraaawn** [comment]
Your CM version is _way_ to old. Please update to latest 1.18.
