### ISSUE TITLE
Console spam with new forge - fluid changes

### ISSUE THREAD

**Issue by sciguyryan** [thraaawn/CompactMachines#98]
The current release of Forge slightly changes the way fluids are handled and as such the following message is now spamming the console. This is with forge 10.13.3.1365.

http://pastebin.com/0jfdiyTm

While it does not initially appear to be causing any harm it is causing the server log files to run up into the 100s of megabyte. I also didn't test in detail that nothing else malfunctioned.

The new versions of Forge are needed for extra utilities and likely the CoFH mods too. As such it may be worth investigating this issue.

If you need any further information please let me know!

**Comment by Cobra1117** [comment]
I also see this bug on Forge 10.13.3.1370, Compact machines 1.17 and 1.18.

**Comment by Cobra1117** [comment]
Any chance that we could get a beta build of this? The uploaded (preview 1.19) source doesn't want to compile for some reason. (I haven't modded in a while, so maybe things have changed, but it seems to be having some issues with the Mekanism API when I try to compile.)
